site_name: TaelgarVerse
theme:
  name: material
  features: 
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - md_in_html
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
hooks:
  - scripts/export_vault.py
plugins:
  - search  
  - callouts
  - literate-nav:
      nav_file: toc.md
  - section-index